=== gsilver/a11ysupport.io/data/schema/dev-test.json
{
  "$id": "http://accessibilitysupported.com/dev-test.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "at": {
      "type": "object",
      "properties": {
        "browsers": {
          "type": "object",
          "properties": {
            "chrome": {
              "$ref": "#/definitions/browser"
            },
            "and_chr": {
              "$ref": "#/definitions/browser"
            },
            "edge": {
              "$ref": "#/definitions/browser"
            },
            "firefox": {
              "$ref": "#/definitions/browser"
            },
            "and_ff": {
              "$ref": "#/definitions/browser"
            },
            "ie": {
              "$ref": "#/definitions/browser"
            },
            "ios_saf": {
              "$ref": "#/definitions/browser"
            },
            "safari": {
              "$ref": "#/definitions/browser"
            }
          }
        }
      },
      "required": ["browsers"]
    },
    "browser": {
      "type": "object",
      "properties": {
        "at_version": {
          "type": "string"
        },
        "browser_version": {
          "type": "string"
        },
        "os_version": {
          "type": "string",
          "description": "The OS version indicates what accessibility APIs are in use"
        },
        "support": {
          "description": "Is the combination supported? y=yes, p=partial, n=no, na=not-applicable. If partial, please provide extra documentation as to why.",
          "type": "string",
          "enum": ["y", "p", "n", "na", "u"]
        },
        "date": {
          "description": "The date is required to help us determine which support points have priority for testing.",
          "type": "string",
          "format": "date"
        }
      },
      "required": ["support", "at_version", "browser_version", "os_version", "date"]
    },
    "history": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        },
        "message": {
          "type": "string"
        }
      },
      "required": ["date", "message"]
    },
    "state_or_property": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["title", "value"]
    }
  },
  "properties": {
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": ["aam", "external", "custom"],
      "description": "The type indicates the kind of test. An AAM test checks for proper accessibility api mappings according to the AAM standards. An external test brings in the results from a test published on another site. A custom test describes the exact expectations and steps."
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "keywords": {
      "description": "Key words that are used to help find features in a search",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "url": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["title", "url"]
    },
    "supports_sr": {
      "type": "boolean"
    },
    "supports_vc": {
      "type": "boolean",
      "description": "A test will usually only support VC if the target element is interactive."
    },
    "sr_instructions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "vc_instructions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "css_target": {
      "type": "string"
    },
    "expected": {
      "type": "object",
      "properties": {
        "role": {
          "type": "string"
        },
        "accessible_name": {
          "type": "string"
        },
        "accessible_description": {
          "type": "string"
        },
        "states_and_properties": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/state_or_property"
          }
        }
      },
      "required": ["role", "accessible_name", "accessible_description", "states_and_properties"]
    },
    "history": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/history"
      }
    },
    "core_support": {
      "type": "array"
    },
    "extended_support": {
      "type": "array"
    },
    "core_support_string": {
      "type": "string"
    },
    "extended_support_string": {
      "type": "string"
    },
    "at": {
      "type": "object",
      "properties": {
        "jaws": {
          "$ref": "#/definitions/at"
        },
        "nvda": {
          "$ref": "#/definitions/at"
        },
        "vo_ios": {
          "$ref": "#/definitions/at"
        },
        "vo_macos": {
          "$ref": "#/definitions/at"
        },
        "windoweyes": {
          "$ref": "#/definitions/at"
        },
        "narrator": {
          "$ref": "#/definitions/at"
        },
        "android": {
          "$ref": "#/definitions/at"
        },
        "dragon_win": {
          "$ref": "#/definitions/at"
        },
        "dragon_mac": {
          "$ref": "#/definitions/at"
        }
      }
    }
  },
  "required": [
    "title",
    "type",
    "description",
    "supports_sr",
    "supports_vc",
    "history",
    "at"
  ],
  "anyOf": [
    {
      "properties": {
        "type": { "enum": ["aam"] }
      },
      "required": ["expected", "css_target"]
    },
    {
      "properties": {
        "type": { "enum": ["external"] }
      },
      "required": ["url"]
    },
    {
      "properties": {
        "type": { "enum": ["custom"] }
      },
      "required": ["css_target", "sr_instructions", "vc_instructions"]
    }
  ]
}

=== gsilver/a11ysupport.io/data/tests/html_td_element_with_row_header_custom.json
{
  "type": "custom",
  "title": "td element with a row header (scope=\"row\")",
  "description": "This test verifies that the row header is announced for associated td elements when the scope=\"row\" attribute is used.",
  "keywords": ["scope=\"row\""],
  "supports_sr": true,
  "supports_vc": false,
  "css_target": "#target",
  "sr_instructions": [
    "Use the screen reader to navigate to the target cell. The target cell contains the text \"target\"",
    "The test passes if the row header \"row one header\" was announced with the target cell."
  ],
  "vc_instructions": [],
  "history": [
    {
      "date": "2018-07-29",
      "message": "Sample data has been added. This data has not been verified."
    }
  ],
  "at": {

  }
}

=== gsilver/a11ysupport.io/data/tests/aria_hidden_text_input_custom.json
{
  "type": "custom",
  "title": "aria-hidden on a text input",
  "description": "This test uses `aria-hidden='true'` on a div containing a text input",
  "supports_sr": true,
  "supports_vc": true,
  "css_target": "#target",
  "sr_instructions": [
    "Use the screen reader to navigate through the page",
    "The test passes if the target input and associated label were not announced"
  ],
  "vc_instructions": [
    "Use the VC software to activate the form control by saying \"click 'your name'\"",
    "The test passes if the target form control could not be found"
  ],
  "history": [
    {
      "date": "2018-08-02",
      "message": "NVDA/Firefox support added. Thank you @ShadowBB"
    },
    {
      "date": "2018-07-22",
      "message": "Sample data has been added. This data has not been verified."
    }
  ],
  "at": {
    "nvda": {
      "browsers": {
        "firefox": {
          "at_version": "2018.2.1",
          "browser_version": "61.0.1",
          "os_version": "17134.165",
          "support": "y",
          "output": [
            {
              "command": "down arrow",
              "command_name": "read next item",
              "output": "(target not read)",
              "result": "pass"
            },
            {
              "command": "tab",
              "command_name": "next focusable item",
              "output": "Your name edit has auto complete",
              "result": "pass"
            }
          ],
          "date": "2018-08-02",
          "notes": "When using focus mode (tab key) the control is still read. This is because the `aria-hidden=\"true\"` does not make elements in the sub tree inert. It is the author's responsibility to make controls inert. See [nvaccess/nvda #5014](https://github.com/nvaccess/nvda/issues/5014) for more information."
        }
      }
    }
  }
}

=== gsilver/a11ysupport.io/data/tests/html_td_element_with_th(scope-row)_custom.json
{
  "type": "custom",
  "title": "td element with a row header (th[scope=\"row\"])",
  "description": "This test verifies that the row header is announced for associated td elements when the scope=\"row\" attribute is used.",
  "keywords": ["scope=\"row\""],
  "supports_sr": true,
  "supports_vc": false,
  "css_target": "#target",
  "sr_instructions": [
    "Use the screen reader to navigate to the target cell. The target cell contains the text \"target\"",
    "The test passes if the row header \"row one header\" was announced with the target cell. If some commands work and others do not, the test should be marked as 'partial support'."
  ],
  "vc_instructions": [],
  "history": [
    {
      "date": "2018-07-29",
      "message": "Sample data has been added. This data has not been verified."
    }
  ],
  "at": {
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.13.6",
          "browser_version": "11.1.2",
          "os_version": "10.13.6",
          "support": "p",
          "date": "2018-07-29",
          "output": "target, column 2 of 2",
          "notes": "When the table is first announced by VO, it states that you can \"navigate the cells within this table by pressing Control-Option, and then Up Arrow, Down Arrow, Left Arrow, or Right Arrow\". When navigating by Control+Option + Left/Right Arrows, the test fails. The test passes when navigating by Control+Option Up/Down Arrows."
        }
      }
    }
  }
}

=== gsilver/a11ysupport.io/data/tests/html_label_element_explicit_aam.json
{
  "type": "aam",
  "title": "Explicit label",
  "description": "This style of labeling depends on IDs.",
  "supports_sr": true,
  "supports_vc": true,
  "css_target": "#target",
  "expected": {
    "role": "textbox",
    "accessible_name": "Your name",
    "accessible_description": "",
    "states_and_properties": []
  },
  "history": [
    {
      "date": "2018-07-06",
      "message": "Sample data has been added. This data has not been verified."
    }
  ],
  "at": {
    "jaws": {
      "browsers": {
        "ie": {
          "at_version": "18",
          "browser_version": "11",
          "os_version": "17134",
          "support": "y",
          "date": "2018-07-21"
        },
        "edge": {
          "at_version": "18",
          "browser_version": "17",
          "os_version": "17134",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    },
    "nvda": {
      "browsers": {
        "firefox": {
          "at_version": "2018.1.1",
          "browser_version": "60",
          "os_version": "17134",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "11.4",
          "browser_version": "11.4",
          "os_version": "11.4",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.13.5",
          "browser_version": "11.1.1",
          "os_version": "10.13.5",
          "support": "y",
          "output": [
            {
              "command": "tab",
              "command_name": "next focusable item",
              "output": "your name, edit text",
              "result": "pass"
            }
          ],
          "date": "2018-07-21"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "10",
          "browser_version": "17",
          "os_version": "17134",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    },
    "talkback": {
      "browsers": {
        "and_chr": {
          "at_version": "6.2",
          "browser_version": "67",
          "os_version": "8.1",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    },
    "dragon_win": {
      "browsers": {
        "chrome": {
          "at_version": "13",
          "browser_version": "60",
          "os_version": "17134",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    }
  }
}

=== gsilver/a11ysupport.io/data/tests/aria_alert_role_dom_functions_external.json
{
  "type": "external",
  "title": "aria alert role via DOM functions",
  "description": "Uses method 1: createElement(), insertAttribute(), createTextNode() and appendchild()",
  "url": {
    "title": "ARIA alert support - TPG Blog",
    "url": "https://developer.paciellogroup.com/blog/2017/04/aria-alert-support/"
  },
  "supports_sr": true,
  "supports_vc": false,
  "history": [
    {
      "date": "2018-07-21",
      "message": "Sample data has been added. This data has not been verified."
    }
  ],
  "at": {
    "jaws": {
      "browsers": {
        "firefox": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "chrome": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "ie": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "edge": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "u",
          "date": "2018-07-21"
        }
      }
    },
    "nvda": {
      "browsers": {
        "firefox": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "chrome": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "ie": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "edge": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "n",
          "date": "2018-07-21"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "chrome": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "firefox": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        },
        "chrome": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "y",
          "date": "2018-07-21"
        }
      }
    },
    "narrator": {
      "browsers": {
        "ie": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "n",
          "date": "2018-07-21"
        },
        "edge": {
          "at_version": "unknown",
          "browser_version": "unknown",
          "os_version": "unknown",
          "support": "n",
          "date": "2018-07-21"
        }
      }
    }
  }
}

=== gsilver/a11ysupport.io/data/tests/css_generated_content_aam.json
{
  "type": "aam",
  "title": "Standard test",
  "description": "This test uses ::before and ::after pseudo classes to add content to static text",
  "supports_sr": true,
  "supports_vc": false,
  "css_target": "#target",
  "expected": {
    "role": "",
    "accessible_name": "This is generated content.",
    "accessible_description": "",
    "states_and_properties": []
  },
  "history": [
    {
      "date": "2018-07-06",
      "message": "Sample data has been added. This data has not been verified."
    }
  ],
  "at": {
    "jaws": {
      "browsers": {
        "firefox": {
          "at_version": "18",
          "browser_version": "60",
          "os_version": "17134",
          "support": "y",
          "output": [
            {
              "command": "down arrow",
              "command_name": "read next item",
              "output": "This is generated content.",
              "pass": "y"
            }
          ],
          "date": "2018-07-21"
        },
        "ie": {
          "at_version": "18",
          "browser_version": "11",
          "os_version": "17134",
          "support": "n",
          "output": [
            {
              "command": "down arrow",
              "command_name": "read next item",
              "output": "is generated",
              "pass": "n"
            }
          ],
          "date": "2018-07-21"
        },
        "edge": {
          "at_version": "18",
          "browser_version": "17",
          "os_version": "17134",
          "support": "y",
          "output": [
            {
              "command": "down arrow",
              "command_name": "read next item",
              "output": "This is generated content.",
              "result": "pass"
            }
          ],
          "date": "2018-07-21"
        }
      }
    },
    "nvda": {
      "browsers": {
        "firefox": {
          "at_version": "2018.1.1",
          "browser_version": "60",
          "os_version": "17134",
          "support": "y",
          "output": [
            {
              "command": "down arrow",
              "command_name": "read next item",
              "output": "This is generated content.",
              "result": "pass"
            }
          ],
          "date": "2018-07-21"
        }
      }
    }
  }
}
